apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pwm-app
  template:
    metadata:
      labels:
        app: pwm-app
    spec:
      containers:
        - name: pwm-app
          image: 9cps/pwm-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: pwm-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pwm-postgres:5432/myapp_db
            - name: SPRING_DATASOURCE_USERNAME
              value: myapp_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pwm-secrets
                  key: db-password
            - name: SPRING_REDIS_HOST
              value: pwm-redis
            - name: SPRING_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: pwm-app
spec:
  selector:
    app: pwm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
