apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwm-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwm-postgres
  template:
    metadata:
      labels:
        app: pwm-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: myapp_db
            - name: POSTGRES_USER
              value: myapp_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pwm-secrets
                  key: db-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pwm-postgres
spec:
  selector:
    app: pwm-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
